name: "Tests CI"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - name: Install dependencies
        run: nix develop
      - name: Setup database
        run: nix develop --command sqlx database create
      - name: Run tests
        run: nix develop --command cargo test